function results = run_digital_twin_scenarios(config)
%RUN_DIGITAL_TWIN_SCENARIOS Compare the declared RETINA-NEXUS scenarios.
% Returns an operational capacity-planning table; this is not clinical
% validation and does not estimate diagnostic performance.

if nargin < 1 || isempty(config)
    config = struct();
end

scenarioNames = ["NORMAL LOAD", "HIGH LOAD", "LOW BANDWIDTH", ...
    "HIGH UNGRADABLE RATE", "LIMITED SPECIALIST CAPACITY"];
rows = zeros(numel(scenarioNames), 9);

for index = 1:numel(scenarioNames)
    summary = retina_nexus_digital_twin(config, scenarioNames(index));
    rows(index, :) = [summary.counts.arrivals, ...
        summary.counts.completed_outcomes, summary.throughput_per_day, ...
        summary.queue.max_specialist_queue, ...
        summary.queue.mean_specialist_waiting_minutes, ...
        summary.staff_utilization.acquisition, ...
        summary.staff_utilization.ai_processing, ...
        summary.staff_utilization.specialist_review, ...
        summary.resource_requirements.specialists_at_target_utilization];
end

results = array2table(rows, 'VariableNames', {'Arrivals', ...
    'CompletedOutcomes', 'ThroughputPerDay', 'MaxSpecialistQueue', ...
    'MeanSpecialistWaitMinutes', 'AcquisitionUtilization', ...
    'AIUtilization', 'SpecialistUtilization', ...
    'RequiredSpecialistsAtTargetUtilization'});
results.Scenario = scenarioNames';
results = movevars(results, 'Scenario', 'Before', 1);
end
