import { ArrowRight, Plus, Search, UserRound, Users } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { DataState, ErrorState, EmptyState } from '../components/DataState';
import { PageIntro } from '../components/PageIntro';
import { StatusBadge } from '../components/StatusBadge';
import { getPatients } from '../services/api';
import type { Patient } from '../types';

export function PatientsPage() {
  const [patients, setPatients] = useState<Patient[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  function load() { setLoading(true); setError(''); getPatients().then(setPatients).catch((requestError) => setError(requestError instanceof Error ? requestError.message : 'Unable to load patient directory.')).finally(() => setLoading(false)); }
  useEffect(load, []);
  const filtered = useMemo(() => patients.filter((patient) => patient.anonymized_identifier.toLowerCase().includes(query.toLowerCase())), [patients, query]);
  return <div className="space-y-6"><PageIntro eyebrow="Care records" title="Patient directory" description="Anonymized records connected to screening activity in this workspace." action={<Link to="/screening/new" className="btn-primary"><Plus size={16} /> Add through screening</Link>} /><div className="grid gap-4 sm:grid-cols-3"><InfoCard icon={Users} label="Patients in registry" value={patients.length} /><InfoCard icon={UserRound} label="Active workspace" value="Live" tone="teal" /><InfoCard icon={UserRound} label="Identifier policy" value="Anonymous" tone="amber" /></div><div className="surface overflow-hidden"><div className="flex flex-col justify-between gap-3 border-b border-line px-5 py-4 sm:flex-row sm:items-center sm:px-6"><div><h2 className="section-title text-base font-extrabold">Patient directory</h2><p className="mt-1 text-xs text-slate-400">Minimal metadata by design</p></div><div className="flex items-center gap-2 rounded-xl border border-line bg-mist px-3 py-2"><Search size={14} className="text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search identifier" className="w-48 bg-transparent text-xs font-semibold outline-none" /></div></div>{loading ? <DataState label="Loading patient directory" /> : error ? <div className="p-5"><ErrorState message={error} onRetry={load} /></div> : filtered.length === 0 ? <EmptyState title="No matching patients" detail="No anonymized record matches this search." /> : <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead><tr className="border-b border-line bg-mist text-[10px] font-bold uppercase tracking-wider text-slate-400"><th className="px-6 py-3">Identifier</th><th className="px-4 py-3">Age group</th><th className="px-4 py-3">Created</th><th className="px-4 py-3">Status</th><th /></tr></thead><tbody>{filtered.map((patient) => <tr key={patient.id} className="border-b border-line last:border-0 hover:bg-mist/50"><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-teal-50 text-xs font-extrabold text-teal-700">{patient.anonymized_identifier.slice(-2)}</div><span className="text-xs font-bold text-ink">{patient.anonymized_identifier}</span></div></td><td className="px-4 py-4 text-xs text-slate-500">{patient.age_group ?? 'Not recorded'}</td><td className="px-4 py-4 text-xs text-slate-500">{formatDate(patient.created_at)}</td><td className="px-4 py-4"><StatusBadge tone="success">Active</StatusBadge></td><td className="px-4 py-4 text-right"><Link to="/screening/new" className="inline-flex rounded-lg p-2 text-slate-400 hover:bg-teal-50 hover:text-teal-700"><ArrowRight size={15} /></Link></td></tr>)}</tbody></table></div>}</div></div>;
}

function InfoCard({ icon: Icon, label, value, tone = 'blue' }: { icon: typeof Users; label: string; value: string | number; tone?: 'blue' | 'teal' | 'amber' }) { const styles = { blue: 'bg-blue-50 text-blue-600', teal: 'bg-teal-50 text-teal-600', amber: 'bg-amber-50 text-amber-600' }; return <div className="surface flex items-center gap-4 p-5"><div className={`rounded-xl p-3 ${styles[tone]}`}><Icon size={20} /></div><div><p className="eyebrow">{label}</p><p className="mt-1 text-xl font-extrabold text-ink">{value}</p></div></div>; }
function formatDate(value?: string) { return value ? new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)) : '—'; }
