import { Bell, ChevronRight, Database, LockKeyhole, Palette, ShieldCheck, SlidersHorizontal, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { DataState } from '../components/DataState';
import { PageIntro } from '../components/PageIntro';
import { StatusBadge } from '../components/StatusBadge';
import { getHealth, getModels } from '../services/api';

const settings = [{ icon: UserRound, title: 'Profile & workspace', detail: 'Manage identity and care team details' }, { icon: ShieldCheck, title: 'Roles & permissions', detail: 'Control access for clinicians and healthcare workers' }, { icon: Bell, title: 'Notifications', detail: 'Choose when review alerts are surfaced' }, { icon: Database, title: 'Storage & retention', detail: 'Configure local or S3-compatible image storage' }, { icon: LockKeyhole, title: 'Security & audit', detail: 'Session, authentication, and audit preferences' }, { icon: Palette, title: 'Appearance', detail: 'Customize the workspace display' }];

export function SettingsPage() { const [health, setHealth] = useState<{ status: string; database: string } | null>(null); const [modelCount, setModelCount] = useState<number | null>(null); useEffect(() => { getHealth().then(setHealth).catch(() => setHealth({ status: 'unavailable', database: 'unavailable' })); getModels().then((items) => setModelCount(items.length)).catch(() => setModelCount(null)); }, []); return <div className="max-w-5xl space-y-7"><PageIntro eyebrow="Workspace" title="Settings" description="Configure the care workspace and understand its current technical posture." /><div className="surface divide-y divide-line">{settings.map(({ icon: Icon, title, detail }) => <button key={title} className="flex w-full items-center gap-4 px-5 py-5 text-left transition hover:bg-mist/60 sm:px-6"><div className="rounded-xl bg-teal-50 p-2.5 text-teal-600"><Icon size={18} /></div><div className="flex-1"><p className="text-sm font-extrabold text-ink">{title}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></div><ChevronRight size={17} className="text-slate-300" /></button>)}</div><div className="surface p-6"><div className="flex items-start gap-3"><div className="rounded-xl bg-amber-50 p-2.5 text-amber-600"><SlidersHorizontal size={18} /></div><div><h2 className="section-title text-base font-extrabold">Environment</h2><p className="mt-1 text-xs text-slate-400">Live signals from the connected API</p></div></div>{!health ? <div className="mt-5"><DataState label="Checking workspace health" /></div> : <div className="mt-6 grid gap-3 sm:grid-cols-3"><Environment label="API" value={health.status} tone={health.status === 'ok' || health.status === 'healthy' ? 'success' : 'warning'} /><Environment label="Database" value={health.database} tone={health.database === 'connected' || health.database === 'ok' ? 'success' : 'warning'} /><Environment label="ML artifacts" value={modelCount == null ? 'Unavailable' : modelCount ? `${modelCount} registered` : 'Not configured'} tone={modelCount ? 'success' : 'warning'} /></div>}</div><div className="rounded-2xl border border-teal-100 bg-teal-50 p-5 text-xs leading-5 text-teal-900"><strong>Prototype boundary:</strong> workspace settings are visualized here, while deployment credentials, model calibration, and retention policy remain environment-managed configuration.</div></div>; }

function Environment({ label, value, tone }: { label: string; value: string; tone: 'success' | 'warning' }) { return <div className="rounded-xl bg-mist p-4"><p className="eyebrow">{label}</p><p className="mt-2 text-sm font-extrabold capitalize text-ink">{value}</p><StatusBadge tone={tone} dot>{tone === 'success' ? 'Connected' : 'Setup required'}</StatusBadge></div>; }
